angular.module(
    'eu.water-switch-on.sip.controllers',
    [
        'ui.bootstrap.dropdown',
        'ui.bootstrap.alert',
        'ui.bootstrap.modal',
        'mgcrea.ngStrap.popover',
        'mgcrea.ngStrap.tooltip',
        'ui.bootstrap.accordion',
        'leaflet-directive',
        'ui.bootstrap.progressbar',
        'ui.bootstrap.buttons'
    ]
);
