angular.module(
    'eu.water-switch-on.sip.controllers',
    [
        'ui.bootstrap.dropdown',
        'ui.bootstrap.alert',
        'ui.bootstrap.modal',
        'mgcrea.ngStrap.popover',
        'ui.bootstrap.accordion',
        'leaflet-directive',
        'ui.bootstrap.progressbar'
    ]
);
